name = "gltf-viewer"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./.vercel/output/static"


main = "./.vercel/output/static/_worker.js"
workers_dev = true